exception: fix names of function calls
TODO Neither exit() nor syscall_exit() is available to the
  kernel. Need a way to cause process to exit with rc -1.
  - Could route code into syscall_handler
  - Could do "whatever it is that syscall_exit does" in a
    process_* function.
      ^ I vote for this option